from . import Base

from sqlalchemy import Column, BigInteger, Float, VARCHAR, ForeignKey

class DIASource(Base):
    __tablename__ = "diasources"

    diaSourceId = Column('diasourceid', BigInteger, primary_key=True)
    CcdVisitId = Column('ccdvisitid', BigInteger)
    diaobjectid = Column(BigInteger)
    midpointtai = Column("midpointtai", Float(2))
    ssObjectId = Column("ssobjectid", BigInteger) 
    mag = Column(Float)
    magSigma = Column("magsigma", Float)
    filter = Column(VARCHAR(1)) # filter name cause issues later on
    # (handle relationships) ssobjectid
    '''
    parentdiasourceid = Column(BigInteger)
    prv_procorder = Column(Integer, name="prv_procorder")
    ssobjectreassoctime = Column(DateTime)
    
    ra = Column(Float(2))
    rasigma = Column(Float(2)) 
    decl = Column(Float(2))
    declsigma = Column(Float)
    ra_decl_cov = Column(Float)
    x = Column(Float)
    xsigma = Column(Float)
    y = Column(Float)
    ysigma = Column(Float)
    x_y_cov = Column(Float)
    
    
    magsigma = Column(Float)
    psflux = Column(Float)
    psfluxsigma = Column(Float)
    psra = Column(Float(2))
    psRaSigma = Column(Float)
    psdecl = Column(Float)
    psdeclsigma = Column(Float)
    psflux_psra_cov = Column(Float)
    psFlux_psDecl_cov = Column(Float)
    psra_psdecl_cov = Column(Float)
    psLnL = Column(name="pslnl", type=Float)
    psChi2 = Column(name="psChi2", type=Float)
    psNdata = Column(name="psndata", type=Integer)
    trailFlux = Column(name="trailflux", type=Float)
    trailRa =  Column(name="trailra", type=Float)
    trailRaSigma = Column(name="trailrasigma", type=Float)
    trailDecl  = Column(name="traildecl", type=Float)
    trailDeclSigma= Column(name="traildeclsigma", type=Float)
    trailLength= Column(name="traillength", type=Float)
    trailLengthSigma= Column(name="traillengthsigma", type=Float)
    trailAngle= Column(name="trailangle", type=Float)
    trailAngleSigma= Column(name="trailanglesigma", type=Float)
    trailFlux_trailRa_Cov= Column(name="trailflux_trailra", type=Float)
    
    trailFlux_trailDecl_Cov= Column(name="trailrasigma", type=Float)
    trailFlux_trailLength_Cov= Column(name="trailrasigma", type=Float)
    trailFlux_trailAngle_Cov= Column(name="trailrasigma", type=Float)
    trailRa_trailDecl_Cov= Column(name="trailrasigma", type=Float)
    trailRa_trailLength_Cov= Column(name="trailrasigma", type=Float)
    trailRa_trailAngle_Cov= Column(name="trailrasigma", type=Float)
    trailDecl_trailLength_Cov= Column(name="trailrasigma", type=Float)
    trailDecl_trailAngle_Cov= Column(name="trailrasigma", type=Float)
    trailLength_trailAngle_Cov= Column(name="trailrasigma", type=Float)
    trailLnL= Column(name="trailrasigma", type=Float)
    trailChi2= Column(name="trailrasigma", type=Float)
    trailNdata= Column(name="trailrasigma", type=Float)
    dipMeanFlux= Column(name="trailrasigma", type=Float)
    dipMeanFluxSigma= Column(name="trailrasigma", type=Float)
    dipFluxDiff= Column(name="trailrasigma", type=Float)
    dipFluxDiffSigma= Column(name="trailrasigma", type=Float)
    dipRa= Column(name="trailrasigma", type=Float)
    dipRaSigma= Column(name="trailrasigma", type=Float)
    dipDecl= Column(name="trailrasigma", type=Float)
    dipDeclSigma= Column(name="trailrasigma", type=Float)
    dipLength= Column(name="trailrasigma", type=Float)
    dipLengthSigma= Column(name="trailrasigma", type=Float)
    dipAngle= Column(name="trailrasigma", type=Float)
    dipAngleSigma= Column(name="trailrasigma", type=Float)
    dipMeanFlux_dipFluxDiff_Cov= Column(name="trailrasigma", type=Float)
    dipMeanFlux_dipRa_Cov= Column(name="trailrasigma", type=Float)
    dipMeanFlux_dipDecl_Cov= Column(name="trailrasigma", type=Float)
    dipMeanFlux_dipLength_Cov= Column(name="trailrasigma", type=Float)
    dipMeanFlux_dipAngle_Cov= Column(name="trailrasigma", type=Float)
    dipFluxDiff_dipRa_Cov= Column(name="trailrasigma", type=Float)
    dipFluxDiff_dipDecl_Cov= Column(name="trailrasigma", type=Float)
    dipFluxDiff_dipLength_Cov= Column(name="trailrasigma", type=Float)
    dipFluxDiff_dipAngle_Cov= Column(name="trailrasigma", type=Float)
    dipRa_dipDecl_Cov= Column(name="trailrasigma", type=Float)
    dipRa_dipLength_Cov= Column(name="trailrasigma", type=Float)
    dipRa_dipAngle_Cov= Column(name="trailrasigma", type=Float)
    dipDecl_dipLength_Cov= Column(name="trailrasigma", type=Float)
    dipDecl_dipAngle_Cov= Column(name="trailrasigma", type=Float)
    dipLength_dipAngle_Cov= Column(name="trailrasigma", type=Float)
    dipLnL= Column(name="trailrasigma", type=Float)
    dipChi2= Column(name="trailrasigma", type=Float)
    dipNdata= Column(name="trailrasigma", type=Float)
    totFlux= Column(name="trailrasigma", type=Float)
    totFluxErr= Column(name="trailrasigma", type=Float)
    diffFlux= Column(name="trailrasigma", type=Float)
    diffFluxErr= Column(name="trailrasigma", type=Float)
    fpBkgd= Column(name="trailrasigma", type=Float)
    fpBkgdErr= Column(name="trailrasigma", type=Float)
    ixx= Column(name="trailrasigma", type=Float)
    ixxSigma= Column(name="trailrasigma", type=Float)
    iyy= Column(name="trailrasigma", type=Float)
    iyySigma= Column(name="trailrasigma", type=Float)
    ixy= Column(name="trailrasigma", type=Float)
    ixySigma= Column(name="trailrasigma", type=Float)
    ixx_iyy_Cov= Column(name="trailrasigma", type=Float)
    ixx_ixy_Cov= Column(name="trailrasigma", type=Float)
    iyy_ixy_Cov= Column(name="trailrasigma", type=Float)
    ixxPSF= Column(name="trailrasigma", type=Float)
    iyyPSF= Column(name="trailrasigma", type=Float)
    ixyPSF= Column(name="trailrasigma", type=Float)
    extendedness= Column(name="trailrasigma", type=Float)
    spuriousness= Column(name="trailrasigma", type=Float)
    flags= Column(name="trailrasigma", type=Float)
    htmId20= Column(name="trailrasigma", type=Float)
    '''
