"""Schema for SSObjects"""
from . import Base
from sqlalchemy import Column, Integer, Float #, BLOB

class SSObjects(Base):
    __tablename__ = "ssobjects"
    
    
    ssobjectid = Column(Integer, primary_key=True) #Unique identifier.
    discoverysubmissiondate = Column("discoverysubmissiondate",Float) 
    firstobservationdate = Column("firstobservationdate",Float) 
    arc= Column("arc", Float) 
    numobs = Column("numobs",Integer)
    #lcperiodic = Column(BLOB) # need to figure out how to put blob
    moid = Column("moid", Float)
    moidtrueanomaly = Column("moidtrueanomaly", Float)
    moideclipticlongitude = Column("moideclipticlongitude", Float)
    moiddeltav = Column("moiddeltav", Float)
    uh = Column("uh", Float)
    ug12 = Column("ug12", Float)
    uherr = Column("uherr", Float)
    ug12err = Column("ug12err", Float)
    uh_ug12_cov = Column(Float)
    uchi2 = Column("uchi2", Float)
    undata = Column("undata", Integer)
    gh = Column("gh",Float)
    gg12 = Column("gg12", Float)
    gherr = Column("gherr", Float)
    gg12err = Column("gg12err", Float)
    gh_gg12_cov = Column("gh_gg12_cov", Float)
    gchi2 = Column("gchi2", Float)
    gndata = Column("gndata", Integer)
    rh = Column("rh", Float)
    rg12 = Column("rg12", Float)
    rherr = Column("rherr",Float)
    rg12err = Column("rg12err", Float)
    rh_rg12_cov = Column("rh_rg12_cov", Float)
    rchi2 = Column("rchi2", Float)
    rndata = Column("rndata", Integer)
    ih = Column("ih", Float)
    ig12 = Column("ig12", Float)
    iherr = Column("iherr", Float)
    ig12err = Column("ig12err", Float)
    ih_ig12_cov = Column("ih_ig12_cov", Float)
    ichi2 = Column("ichi2", Float)
    indata = Column("indata", Integer)
    zh = Column("zh", Float)
    zg12 = Column("zg12", Float)
    zherr = Column("zherr", Float)
    zg12err = Column("zg12err",Float)
    zh_zg12_cov = Column("zh_zg12_cov", Float)
    zchi2 = Column("zchi2",Float)
    zndata = Column("zndata", Integer)
    yh = Column("yh", Float)
    yg12 = Column("yg12",Float)
    yherr = Column("yherr",Float)
    yg12err = Column("yg12err", Float)
    yh_yg12_cov = Column(Float)
    ychi2 = Column("ychi2", Float)
    yndata = Column("yndata",Integer)
    maxextendedness = Column("maxextendedness",Float)
    minextendedness = Column("minextendedness",Float)
    medianextendedness = Column("medianextendedness",Float)
    flags = Column("flags", Integer)
